### ISSUE TITLE
additional input for 0d-driver

### ISSUE THREAD

**Issue by ghost** [fabm-model/fabm#3]
Hi,
I am using the 0d driver for a phytoplankton model. In addition to light and temperature, I want to read input data for zooplankton and other quantities. I modified the 0d-driver to read this additional non-standart input-data.
Is there another way to deal with it? In the current state my model will not work with the original 0d-driver.

**Comment by jornbr** [comment]
There is another way: you can specify additional forcing variables by providing an additional configuration file, `input.yaml`. This file describes additional forcing variables, which can either be set to a constant value, or read in from a file with a time series. For instance, it could contain:

```
mole_fraction_of_carbon_dioxide_in_air:
  constant_value: 400
zoo/c:
  file: zooplankton.dat
```

Jorn
